"$schema" = "./node_modules/wrangler/config-schema.json"
name = "tsukeai-web"
main = ".open-next/worker.js"
compatibility_date = "2026-05-11"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
API_BASE_URL = "https://tsukeai-api.yaurevoci.workers.dev"